### ISSUE TITLE
NPE when the import module is not available in the distribution

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-distribution#1613]
**Description:**
Getting an NPE when the import module is not available in the pack. In the sample, it's `ballerinax/java.jdbc`.
Better if we can have a proper error message.

```
Compiling source
        testBal.bal
Exception in thread "main" java.lang.NullPointerException
        at io.ballerina.cli.launcher.Main.main(Main.java:63)
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
SL Alpha 5
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
```ballerina
import ballerina/lang.'transaction as transactions;
import ballerina/io;
import ballerinax/java.jdbc;

public function main() returns error? {
    // The JDBC Client for the H2 database.
    jdbc:Client dbClient =
                check new (url = "jdbc:h2:file:./local-transactions/accountdb",
                           user = "test", password = "test");

    // Create the database table and populate some records.
    _ = check dbClient->execute("CREATE TABLE IF NOT EXISTS ACCOUNT " +
                                "(ID INTEGER, BALANCE DECIMAL, " +
                                "PRIMARY KEY(id))");
    _ = check dbClient->execute("INSERT INTO ACCOUNT VALUES (1, 2500.0)");
    _ = check dbClient->execute("INSERT INTO ACCOUNT VALUES (2, 1000.0)");

    // This is a `transaction` statement block. It is a must to have either
    // a commit action or a rollback statement in it. The transaction scope ends after
    // the commit action or rollback statement.
    transaction {
        // Execute database operations within the transaction
        var creditResult = dbClient->execute(
                                       "UPDATE ACCOUNT " +
                                       "SET BALANCE=BALANCE+500.0 WHERE ID=1");
        var debitResult = dbClient->execute(
                                       "UPDATE ACCOUNT " +
                                       "SET BALANCE=BALANCE-500.0 WHERE ID=2");

        // Returns information about the current transactions.
        transactions:Info transInfo = transactions:info();
        io:println("Transaction Info: ", transInfo);

        // The `commit` action performs the commit operation of the current transaction.
        // The result of the commit action will be either `error` or `()`.
        var commitResult = commit;
        if commitResult is () {
            // Operations to be executed after the transaction are committed successfully.
            io:println("Transaction committed");
            io:println("Account Credit: ", creditResult);
            io:println("Account Debit: ", debitResult);
        } else {
            // Operations to be executed if the transaction commit failed.
            io:println("Transaction failed");
        }
    }

    _ = check dbClient->execute("DROP TABLE ACCOUNT");
    
    // Close the JDBC client.
    check dbClient.close();
}
```

**Related Issues:**

**Comment by azinneera** [comment]
AFAIU, this occurs due to the way the exception handling is done when BIR is loaded.

Got the following stack trace when we debugged to find the cause.

```
org.ballerinalang.compiler.BLangCompilerException
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.definePackage(BIRPackageSymbolEnter.java:197)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.definePackage(BIRPackageSymbolEnter.java:170)
	at io.ballerina.projects.ModuleContext.loadPackageSymbolInternal(ModuleContext.java:443)
	at io.ballerina.projects.ModuleCompilationState$6.compile(ModuleCompilationState.java:178)
	at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:329)
	at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:176)
	at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:168)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:97)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:206)
	at io.ballerina.projects.Package.getCompilation(Package.java:131)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:68)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:272)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)
Caused by: java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.lookupSymbol(SymbolResolver.java:531)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.lookupSymbolInMainSpace(SymbolResolver.java:560)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readType(BIRPackageSymbolEnter.java:1163)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.readBType(BIRPackageSymbolEnter.java:584)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readTypeFromCp(BIRPackageSymbolEnter.java:1036)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readType(BIRPackageSymbolEnter.java:1324)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.readBType(BIRPackageSymbolEnter.java:584)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readTypeFromCp(BIRPackageSymbolEnter.java:1036)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readType(BIRPackageSymbolEnter.java:1117)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.readBType(BIRPackageSymbolEnter.java:584)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readTypeFromCp(BIRPackageSymbolEnter.java:1036)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readType(BIRPackageSymbolEnter.java:1223)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.readBType(BIRPackageSymbolEnter.java:584)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.defineFunction(BIRPackageSymbolEnter.java:392)
	at org.wso2.ballerinalang.util.LambdaExceptionUtils.lambda$rethrow$0(LambdaExceptionUtils.java:45)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.defineSymbols(BIRPackageSymbolEnter.java:366)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.definePackage(BIRPackageSymbolEnter.java:251)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.definePackage(BIRPackageSymbolEnter.java:219)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.definePackage(BIRPackageSymbolEnter.java:193)
	... 14 more
```

- While loading the BIR, all throwables are caught and rethrown as a `BLangCompilerException` at https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java#L197. When creating the `BLangCompilerException`, the message from the original exception has been added blindly. In this case, the exception that is caught happens to be an NP, and thus `null` is passed as the message to create the `BLangCompilerException`.

- In CLI, we catch the `BLangCompilerException` and check for the `e.getMessage()` to decide on the way we should exit the command. https://github.com/ballerina-platform/ballerina-lang/blob/cafd47dd7d8e39699b3fd5d86fe4cc213b670a95/cli/ballerina-cli/src/main/java/io/ballerina/cli/launcher/Main.java#L62. At this point, when the cause of the exception an NP, a new NP is thrown since the message of the caught exception (NP) is null.

IMO, we should add a string such as `error while loading the bir` instead of blindly passing the `e.getMessage()` when creating the `BLangCompilerException`.

**Comment by azinneera** [comment]
AFAIU, this occurs due to the way the exception handling is done when BIR is loaded.

Got the following stack trace when we debugged to find the cause.

```
org.ballerinalang.compiler.BLangCompilerException
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.definePackage(BIRPackageSymbolEnter.java:197)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.definePackage(BIRPackageSymbolEnter.java:170)
	at io.ballerina.projects.ModuleContext.loadPackageSymbolInternal(ModuleContext.java:443)
	at io.ballerina.projects.ModuleCompilationState$6.compile(ModuleCompilationState.java:178)
	at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:329)
	at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:176)
	at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:168)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:97)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:206)
	at io.ballerina.projects.Package.getCompilation(Package.java:131)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:68)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:272)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)
Caused by: java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.lookupSymbol(SymbolResolver.java:531)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.lookupSymbolInMainSpace(SymbolResolver.java:560)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readType(BIRPackageSymbolEnter.java:1163)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.readBType(BIRPackageSymbolEnter.java:584)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readTypeFromCp(BIRPackageSymbolEnter.java:1036)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readType(BIRPackageSymbolEnter.java:1324)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.readBType(BIRPackageSymbolEnter.java:584)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readTypeFromCp(BIRPackageSymbolEnter.java:1036)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readType(BIRPackageSymbolEnter.java:1117)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.readBType(BIRPackageSymbolEnter.java:584)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readTypeFromCp(BIRPackageSymbolEnter.java:1036)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readType(BIRPackageSymbolEnter.java:1223)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.readBType(BIRPackageSymbolEnter.java:584)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.defineFunction(BIRPackageSymbolEnter.java:392)
	at org.wso2.ballerinalang.util.LambdaExceptionUtils.lambda$rethrow$0(LambdaExceptionUtils.java:45)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.defineSymbols(BIRPackageSymbolEnter.java:366)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.definePackage(BIRPackageSymbolEnter.java:251)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.definePackage(BIRPackageSymbolEnter.java:219)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.definePackage(BIRPackageSymbolEnter.java:193)
	... 14 more
```

- While loading the BIR, all throwables are caught and rethrown as a `BLangCompilerException` at https://github.com/ballerina-platform/ballerina-lang/blob/cafd47dd7d8e39699b3fd5d86fe4cc213b670a95/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java#L197 
When creating the `BLangCompilerException`, the message from the original exception has been added blindly. In this case, the exception that is caught happens to be an NP, and thus `null` is passed as the message to create the `BLangCompilerException`.

- In CLI, we catch the `BLangCompilerException` and check for the `e.getMessage()` to decide on the way we should exit the command. https://github.com/ballerina-platform/ballerina-lang/blob/cafd47dd7d8e39699b3fd5d86fe4cc213b670a95/cli/ballerina-cli/src/main/java/io/ballerina/cli/launcher/Main.java#L62
At this point, when the cause of the exception an NP, a new NP is thrown since the message of the caught exception (NP) is null.

IMO, we should add a string such as `error while loading the bir` instead of blindly passing the message of the caught exception when creating the `BLangCompilerException`.

@pubudu91 @hasithaa WDYT?

**Comment by azinneera** [comment]
AFAIU, this occurs due to the way the exception handling is done when BIR is loaded.

Got the following stack trace when we debugged to find the cause.

```
org.ballerinalang.compiler.BLangCompilerException
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.definePackage(BIRPackageSymbolEnter.java:197)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.definePackage(BIRPackageSymbolEnter.java:170)
	at io.ballerina.projects.ModuleContext.loadPackageSymbolInternal(ModuleContext.java:443)
	at io.ballerina.projects.ModuleCompilationState$6.compile(ModuleCompilationState.java:178)
	at io.ballerina.projects.ModuleContext.compile(ModuleContext.java:329)
	at io.ballerina.projects.PackageCompilation.compileModulesInternal(PackageCompilation.java:176)
	at io.ballerina.projects.PackageCompilation.compileModules(PackageCompilation.java:168)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:97)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:206)
	at io.ballerina.projects.Package.getCompilation(Package.java:131)
	at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:68)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:272)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)
Caused by: java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.lookupSymbol(SymbolResolver.java:531)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SymbolResolver.lookupSymbolInMainSpace(SymbolResolver.java:560)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readType(BIRPackageSymbolEnter.java:1163)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.readBType(BIRPackageSymbolEnter.java:584)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readTypeFromCp(BIRPackageSymbolEnter.java:1036)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readType(BIRPackageSymbolEnter.java:1324)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.readBType(BIRPackageSymbolEnter.java:584)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readTypeFromCp(BIRPackageSymbolEnter.java:1036)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readType(BIRPackageSymbolEnter.java:1117)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.readBType(BIRPackageSymbolEnter.java:584)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readTypeFromCp(BIRPackageSymbolEnter.java:1036)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter$BIRTypeReader.readType(BIRPackageSymbolEnter.java:1223)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.readBType(BIRPackageSymbolEnter.java:584)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.defineFunction(BIRPackageSymbolEnter.java:392)
	at org.wso2.ballerinalang.util.LambdaExceptionUtils.lambda$rethrow$0(LambdaExceptionUtils.java:45)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.defineSymbols(BIRPackageSymbolEnter.java:366)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.definePackage(BIRPackageSymbolEnter.java:251)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.definePackage(BIRPackageSymbolEnter.java:219)
	at org.wso2.ballerinalang.compiler.BIRPackageSymbolEnter.definePackage(BIRPackageSymbolEnter.java:193)
	... 14 more
```

- While loading the BIR, all throwables are caught and rethrown as a `BLangCompilerException` at https://github.com/ballerina-platform/ballerina-lang/blob/cafd47dd7d8e39699b3fd5d86fe4cc213b670a95/compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/BIRPackageSymbolEnter.java#L197 
When creating the `BLangCompilerException`, the message from the original exception has been added blindly. In this case, the exception that is caught happens to be an NP, and thus `null` is passed as the message to create the `BLangCompilerException`.

- In CLI, we catch the `BLangCompilerException` and check for the `e.getMessage()` to decide on the way we should exit the command. https://github.com/ballerina-platform/ballerina-lang/blob/cafd47dd7d8e39699b3fd5d86fe4cc213b670a95/cli/ballerina-cli/src/main/java/io/ballerina/cli/launcher/Main.java#L62
At this point, when the cause of the exception an NP, a new NP is thrown since the message of the caught exception (NP) is null.

IMO, we should add a string such as `error while loading the bir` instead of blindly passing the message of the caught exception when creating the `BLangCompilerException`.

@pubudu91 @hasithaa WDYT?

**Comment by pubudu91** [comment]
+1 for the suggested approach. Ideally we should be able to separate the exceptions due to incompatible BIRs and compiler bugs, instead of catching `Throwable` and rethrowing them as compiler exceptions. But that improvement should come from the compiler side.
