### ISSUE TITLE
Debugger test failures in dev-tools integration tests

### ISSUE THREAD

**Issue by gayaldassanayake** [ballerina-platform/ballerina-distribution#3027]
**Description:**

`org.ballerina.devtools.debug.ModuleBreakpointTest` and `org.ballerina.devtools.debug.ExpressionEvaluationTest` are skipped from `testing.xml` to get PR checks of distribution repo passed. 

This is due to the `org.ballerina.devtools.debug` test failures.

- GitHub workflow log - https://github.com/ballerina-platform/ballerina-distribution/runs/7547707737?check_suite_focus=true#step:4:605
- Stack trace

```log
Ballerina-Dev-Tools-Test-Suite > ballerina-dev-tools-tests > org.ballerina.devtools.debug.ExpressionEvaluationTest > testRemoteCallEvaluation STANDARD_ERROR
    Jul 27, 2022 7:48:40 PM org.ballerinalang.debugger.test.utils.DebugTestRunner evaluateExpression
    WARNING: Error occurred when fetching debug hit variables
    java.util.concurrent.TimeoutException
    	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886)
    	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)
    	at org.ballerinalang.debugger.test.utils.client.DAPRequestManager.evaluate(DAPRequestManager.java:201)
    	at org.ballerinalang.debugger.test.utils.client.DAPRequestManager.evaluate(DAPRequestManager.java:195)
    	at org.ballerinalang.debugger.test.utils.DebugTestRunner.evaluateExpression(DebugTestRunner.java:755)
    	at org.ballerinalang.debugger.test.utils.DebugTestRunner.assertExpression(DebugTestRunner.java:652)
    	at org.ballerina.devtools.debug.ExpressionEvaluationTest.testRemoteCallEvaluation(ExpressionEvaluationTest.java:48)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
    	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
    	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
    	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
    	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
    	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
    	at org.testng.TestRunner.privateRun(TestRunner.java:648)
    	at org.testng.TestRunner.run(TestRunner.java:505)
    	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
    	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
    	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
    	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
    	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
    	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
    	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
    	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
    	at org.testng.TestNG.runSuites(TestNG.java:1049)
    	at org.testng.TestNG.run(TestNG.java:1017)
    	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.runTests(TestNGTestClassProcessor.java:141)
    	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.stop(TestNGTestClassProcessor.java:90)
    	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
    	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
    	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
    	at com.sun.proxy.$Proxy2.stop(Unknown Source)
    	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:135)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
    	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
    	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
    	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
    	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
    	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
    	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
    	at java.base/java.lang.Thread.run(Thread.java:829)


Ballerina-Dev-Tools-Test-Suite > ballerina-dev-tools-tests > org.ballerina.devtools.debug.ExpressionEvaluationTest > testRemoteCallEvaluation FAILED
    org.ballerinalang.test.context.BallerinaTestException at ExpressionEvaluationTest.java:48
        Caused by: java.util.concurrent.TimeoutException at ExpressionEvaluationTest.java:48

Ballerina-Dev-Tools-Test-Suite > ballerina-dev-tools-tests STANDARD_ERROR
    Jul 27, 2022 7:48:45 PM org.ballerinalang.debugger.test.utils.DebugTestRunner terminateDebugSession
    WARNING: Error occurred when terminating debug session
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by NipunaRanasinghe** [comment]
Reopening the issue, since one test failure is remaining to be fixed
